### ISSUE TITLE
Readme Installation Instruction Caused Error

### ISSUE THREAD

**Issue by Swhite9478** [Chaitanyabsprip/present.nvim#2]
When following the README instructions, I was receiving an issue downloading the plugin. I am using Lazy.nvim as opposed to Packer.

It appeared to be a minor typo that was causing the issue. Within the README, the repository is listed as `"chaitanyabspripc/present.nvim"`, and after removing the extraneous 'c' character I was able to pull the plugin.

This is the configuration that worked for me:

```lua
return {
	"chaitanyabsprip/present.nvim",
	event = "VeryLazy",
	config = function()
		require("present").setup({})
	end,
}
```

Cheers!

**Comment by chaitanyabsprip** [comment]
Thank you for pointing that out. I will make the correction.
